// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDataPath() {
  return window['go']['main']['App']['GetDataPath']();
}

export function LoadData(arg1) {
  return window['go']['main']['App']['LoadData'](arg1);
}

export function SaveData(arg1, arg2) {
  return window['go']['main']['App']['SaveData'](arg1, arg2);
}
