// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportData():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetDataPath():Promise<string>;

export function LoadData(arg1:string):Promise<string>;

export function SaveData(arg1:string,arg2:string):Promise<void>;
